---
dependency:
  name: galaxy
driver:
  name: vagrant
platforms:
  - name: centos8
    box: centos/8
    memory: 1024
    cpu: 1
  - name: centos7
    box: centos/7
    memory: 1024
    cpu: 1
provisioner:
  name: ansible
verifier:
  name: ansible
